# CSS/XPath selectors for key elements

login:
  username: "input#email"
  password: "input#password"
  submit: "button[type='submit']"
  launch_challenge: "button:has-text('Launch Challenge')"
  start_journey: "button:has-text('Start Journey')"
  continue_search: "button:has-text('Continue Search')"
  success_indicator: "button:has-text('Inventory Section')"
  inventory_section: "button:has-text('Inventory Section')"


product_card: "div.rounded-lg.border.bg-card"   # wrapper for each product

title: "h3.font-semibold"                       # product name
category: "div.inline-flex"                     # category tag
id: "p.text-xs"                                 # product ID
cost: "dt:has-text('Cost:') + dd"
details: "dt:has-text('Details:') + dd"
inventory: "dt:has-text('Inventory:') + dd"
modified: "dt:has-text('Modified:') + dd"
weight: "dt:has-text('Weight') + dd"
composition: "dt:has-text('Composition:') + dd"
updated: "div.items-center span"                # footer updated date




