# General application settings

# Base URL of the application (overridden if BASE_URL is set in .env)
base_url: "https://example.com"

# Paths (relative to base_url)
login_path: ""
submit_script_path: "/submit-script"

# Data export
output_file: "data/output/products.json"

# Session state
storage_state_file: "data/storage_state.json"

pagination: "infinite_scroll"



